apiVersion: v1
kind: Service
metadata:
  name: prober-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: prober-worker
spec:
  type: ClusterIP
  selector:
    app: prober-worker
  ports:
    - name: metrics
      port: {{ .Values.proberWorker.metricsPort }}
      targetPort: metrics
