apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - name: http
      port: {{ .Values.backendApi.port }}
      targetPort: http
