apiVersion: v1
kind: ConfigMap
metadata:
  name: checks-consumer-config
  namespace: {{ .Values.namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_CHECKS_TOPIC: {{ .Values.kafka.topics.checks | quote }}
  KAFKA_CONSUMER_GROUP: {{ .Values.kafka.consumerGroup | quote }}
  KAFKA_AUTO_OFFSET_RESET: {{ .Values.kafka.autoOffsetReset | quote }}
