apiVersion: v1
kind: Service
metadata:
  name: checks-consumer
  namespace: {{ .Values.namespace }}
  labels:
    app: checks-consumer
spec:
  type: ClusterIP
  selector:
    app: checks-consumer
  ports:
    - name: metrics
      port: {{ .Values.checksConsumer.metricsPort }}
      targetPort: metrics
